# Generated by Django 4.1.7 on 2023-03-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('systemic_name', models.CharField(max_length=250, unique=True, verbose_name='Cистемное название')),
            ],
            options={
                'verbose_name': 'Категория Меню',
                'verbose_name_plural': 'Категории Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('link', models.CharField(blank=True, max_length=250, verbose_name='Ссылка на раздел меню')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='app_menu.treemenucategories', verbose_name='Категория')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_menu.treemenu', verbose_name='Родительское меню')),
            ],
            options={
                'verbose_name': ('Меню',),
                'verbose_name_plural': ('Меню',),
                'ordering': ['name'],
            },
        ),
    ]
